# Generated by Django 5.2.1 on 2025-05-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenuto',
            name='tipologia',
        ),
        migrations.RemoveField(
            model_name='profilo',
            name='immagine',
        ),
        migrations.AddField(
            model_name='contenuto',
            name='album',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contenuto',
            name='anno',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenuto',
            name='artista',
            field=models.CharField(default='Artista sconosciuto', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contenuto',
            name='genere',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilo',
            name='avatar',
            field=models.CharField(choices=[('avatar1.png', 'Avatar 1'), ('avatar2.png', 'Avatar 2'), ('avatar3.png', 'Avatar 3'), ('avatar4.png', 'Avatar 4'), ('avatar5.png', 'Avatar 5'), ('avatar6.png', 'Avatar 6'), ('avatar7.png', 'Avatar 7'), ('avatar8.png', 'Avatar 8'), ('avatar9.png', 'Avatar 9'), ('avatar10.png', 'Avatar 10')], default='avatar1.png', max_length=100),
        ),
        migrations.AddField(
            model_name='profilo',
            name='punti',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contenuto',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='immagini/'),
        ),
        migrations.AlterField(
            model_name='contenuto',
            name='link',
            field=models.URLField(blank=True, help_text='Link YouTube / Spotify / altro', null=True),
        ),
        migrations.AlterField(
            model_name='contenuto',
            name='testo',
            field=models.TextField(help_text='Descrizione, storia o significato del brano'),
        ),
    ]
