# Generated by Django 5.2.1 on 2025-05-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_contenuto_tipologia_remove_profilo_immagine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenuto',
            name='artista',
            field=models.CharField(default='Artista sconosciuto', max_length=100),
        ),
    ]
