# Generated by Django 5.2 on 2025-05-28 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_forum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='descrizione',
            field=models.TextField(default='descrizione di prova mancante default'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CommentoForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data_pubblicazione', models.DateTimeField(auto_now_add=True)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.forum')),
                ('risposta_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.commentoforum')),
            ],
        ),
    ]
