# Generated by Django 5.2 on 2025-05-29 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_forum_descrizione_commentoforum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggiunto_il', models.DateTimeField(auto_now_add=True)),
                ('contenuto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contenuto')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utente', 'contenuto')},
            },
        ),
    ]
